/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 
 */
public class Book extends javax.swing.JFrame {

    /**
     * Creates new form Book
     */
    String x="";
    Customer c;
    int cnt;
    
    String[] arr = new String[] {"-","-","-"};
    public Book(Customer c) {
        this.c=c;       
        initComponents();
        setExtendedState(Book.MAXIMIZED_BOTH); 
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Book your Ride.............");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Your Location :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Destination :");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BITS PILANI", "HAKIMPET", "ALWAL", "TRIMULGHERRY", "PATNY", "SECUNDERABAD" }));
        jComboBox1.setSelectedItem("Bits Pilani");
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BITS PILANI", "HAKIMPET", "ALWAL", "TRIMULGHERRY", "PATNY", "SECUNDERABAD" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Wallet Balance :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Estimated Fare (in Rupees):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("0");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Confirm Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Estimated Time (in minutes) :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Estimated Distance (in km) :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("-");

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setVisible(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Driver's Name  :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("Rating :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("Phone Number :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Booking confirmed!");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("-");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("-");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(636, 636, 636)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(806, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28))))
        );

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jRadioButton1.setText("Logout");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Invalid Click to TRY AGAIN");
        jButton2.setVisible(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Add money");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton5.setText("Pay");
        jButton5.setVisible(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton6.setText("Book again!");
        jButton6.setVisible(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setVisible(false);
        jLabel19.setText("Thank you for choosing us");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Invalid click to Try Again");
        jButton7.setVisible(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(677, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(181, 181, 181)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(178, 178, 178)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jButton3)
                        .addContainerGap(42, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel2)
                                .addGap(92, 92, 92)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(305, 305, 305)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton1))))))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(390, 390, 390))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jButton3))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jLabel19))
                                .addGap(12, 12, 12)))))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomize() throws ClassNotFoundException, SQLException{
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection co = (Connection)
        DriverManager.getConnection("jdbc:mysql://localhost:3306/customer","root","hello@123");
        Statement stat = co.createStatement();
        stat.execute("UPDATE driver SET location='ALWAL' WHERE vehiclenumber='TS09AB1001'");
        stat.execute("UPDATE driver SET location='ALWAL' WHERE vehiclenumber='TS09AB1004'");
        stat.execute("UPDATE driver SET location='ALWAL' WHERE vehiclenumber='TS09AB1009'");
        
        stat.execute("UPDATE driver SET location='BITS PILANI' WHERE vehiclenumber='TS09AB1002'");
        stat.execute("UPDATE driver SET location='BITS PILANI' WHERE vehiclenumber='TS09AB1006'");
        stat.execute("UPDATE driver SET location='BITS PILANI' WHERE vehiclenumber='TS09AB1011'");
        
        stat.execute("UPDATE driver SET location='TRIMULGHERRY' WHERE vehiclenumber='TS09AB1003'");
        stat.execute("UPDATE driver SET location='TRIMULGHERRY' WHERE vehiclenumber='TS09AB1007'");
        stat.execute("UPDATE driver SET location='TRIMULGHERRY' WHERE vehiclenumber='TS09AB1012'");
        
        stat.execute("UPDATE driver SET location='HAKIMPET' WHERE vehiclenumber='TS09AB1010'");
        stat.execute("UPDATE driver SET location='HAKIMPET' WHERE vehiclenumber='TS09AB1017'");
        stat.execute("UPDATE driver SET location='HAKIMPET' WHERE vehiclenumber='TS09AB1005'");
        
        stat.execute("UPDATE driver SET location='SECUNDERABAD' WHERE vehiclenumber='TS09AB1008'");
        stat.execute("UPDATE driver SET location='SECUNDERABAD' WHERE vehiclenumber='TS09AB1015'");
        stat.execute("UPDATE driver SET location='SECUNDERABAD' WHERE vehiclenumber='TS09AB1014'");
        
        stat.execute("UPDATE driver SET location='PATNY' WHERE vehiclenumber='TS09AB1016'"); 
        stat.execute("UPDATE driver SET location='PATNY' WHERE vehiclenumber='TS09AB1018'");        
        stat.execute("UPDATE driver SET location='PATNY' WHERE vehiclenumber='TS09AB1013'"); 
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Object i=jComboBox1.getSelectedItem();
        Object k=jComboBox2.getSelectedItem();
        String b=jLabel7.getText();
        if(i.toString()==k.toString()) {
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jComboBox2.setEnabled(false);
            jComboBox1.setEnabled(false);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
        else if(c.balance<300){
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton2.setText("Low Balance click to Try Again");
            jComboBox2.setEnabled(false);
            jComboBox1.setEnabled(false);
        }
        
        else{
            float maxr=0;

            String s="Select * from driver WHERE location='"+k.toString()+"' AND ontrip='"+"0"+"'" ;
            String v="SELECT MAX(rating) FROM driver WHERE location='"+k.toString()+"' AND ontrip='"+"0"+"' ";
            
            try {  
            System.out.println(cnt+" before book");
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/customer","root","hello@123");
            Statement stmt = con.createStatement();
            Statement m=con.createStatement();
            ResultSet rs = stmt.executeQuery(s);
            ResultSet rs2 = m.executeQuery(v);
            Driver d1;

            while(rs2.next()){
                            maxr=rs2.getFloat(1);
                        }
            m.close();

            while(rs.next()) {
                
    
                String loc=rs.getString("location");
                String trp=rs.getString("ontrip");
                String vehnum=rs.getString("vehiclenumber");
                String dname=rs.getString("drivername");
                String phone=rs.getString("phone");
                float rat=rs.getFloat("rating");
                if(rat==maxr){

                    d1=c.confirmbook(vehnum,dname,phone,rat,loc,trp);
                    stmt.execute("UPDATE driver SET ontrip ='"+'1'+"' where vehiclenumber='"+vehnum+"'");
                    stmt.execute("UPDATE driver SET location ='"+i.toString()+"' where vehiclenumber='"+vehnum+"'");
                    String a="Select * from driver";
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection cone = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/customer","root","hello@123");
                    Statement stm = cone.createStatement(); 
                    stmt.execute("UPDATE customerid SET OnTrip ='"+'1'+"' where Userid='"+c.userid+"'");
                    c.ontrip="1";
                    stm.close();
                    cone.close();  
                    x=vehnum;
                    jPanel2.setVisible(true);
                    jLabel17.setText(d1.dname);
                    jLabel18.setText(d1.phone);
                    jLabel16.setText(String.valueOf(d1.ratin));
                    cnt=cnt+1;
                    System.out.println(cnt+"after book");
                    //int ctr=cnt%3;
                    break;
                }
                else{
                    continue;
                }
                               
            }
            
            stmt.close();
            con.close();        
            jPanel2.setVisible(true);     
            jButton5.setVisible(true);
            }
            catch(SQLException se){
                System.out.println(se);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            } 
            jButton1.setVisible(false);            
            jComboBox2.setEnabled(false);
            jComboBox1.setEnabled(false);
          
        }
    }
    private String[] givedetail(String a,String b){
        String estfare="-";
        String estdis="-";
        String esttime="-";
        if((a.equals("SECUNDERABAD")&&b.equals("BITS PILANI"))||(b.equals("SECUNDERABAD")&&a.equals("BITS PILANI"))){
            estfare=String.valueOf(300);
            estdis=String.valueOf(25);
            esttime=String.valueOf(75);    
        }
        else if((a.equals("PATNY")&&b.equals("BITS PILANI"))||(b.equals("PATNY")&&a.equals("BITS PILANI"))){
            estfare=String.valueOf(240);
            estdis=String.valueOf(20);
            esttime=String.valueOf(60);    
        }
        else if((a.equals("SECUNDERABAD")&&b.equals("HAKIMPET"))||(b.equals("SECUNDERABAD")&&a.equals("HAKIMPET"))){
            estfare=String.valueOf(240);
            estdis=String.valueOf(20);
            esttime=String.valueOf(60);     
        }
        else if((a.equals("PATNY")&&b.equals("HAKIMPET"))||(b.equals("PATNY")&&a.equals("HAKIMPET"))){
            estfare=String.valueOf(180);
            estdis=String.valueOf(15);
            esttime=String.valueOf(45);    
        }
        else if((a.equals("SECUNDERABAD")&&b.equals("ALWAL"))||(b.equals("SECUNDERABAD")&&a.equals("ALWAL"))){
            estfare=String.valueOf(180);
            estdis=String.valueOf(15);
            esttime=String.valueOf(45);    
        }
        else if((a.equals("TRIMULGHERRY")&&b.equals("BITS PILANI"))||(b.equals("TRIMULGHERRY")&&a.equals("BITS PILANI"))){
            estfare=String.valueOf(180);
            estdis=String.valueOf(15);
            esttime=String.valueOf(45);    
        }
        else if((a.equals("ALWAL")&&b.equals("BITS PILANI"))||(b.equals("ALWAL")&&a.equals("BITS PILANI"))){
            estfare=String.valueOf(120);
            estdis=String.valueOf(10);
            esttime=String.valueOf(30);    
        }
        else if((a.equals("PATNY")&&b.equals("ALWAL"))||(b.equals("PATNY")&&a.equals("ALWAL"))){
            estfare=String.valueOf(120);
            estdis=String.valueOf(10);
            esttime=String.valueOf(30);   
        }
        else if((a.equals("SECUNDERABAD")&&b.equals("TRIMULGHERRY"))||(b.equals("SECUNDERABAD")&&a.equals("TRIMULGHERRY"))){
            estfare=String.valueOf(120);
            estdis=String.valueOf(10);
            esttime=String.valueOf(30);     
        }
        else if((a.equals("TRIMULGHERRY")&&b.equals("HAKIMPET"))||(b.equals("TRIMULGHERRY")&&a.equals("HAKIMPET"))){
            estfare=String.valueOf(120);
            estdis=String.valueOf(10);
            esttime=String.valueOf(30);    
        }
        else if((a.equals("ALWAL")&&b.equals("HAKIMPET"))||(b.equals("ALWAL")&&a.equals("HAKIMPET"))){
            estfare=String.valueOf(60);
            estdis=String.valueOf(5);
            esttime=String.valueOf(15);    
        }
        else if((a.equals("HAKIMPET")&&b.equals("BITS PILANI"))||(b.equals("HAKIMPET")&&a.equals("BITS PILANI"))){
            estfare=String.valueOf(60);
            estdis=String.valueOf(5);
            esttime=String.valueOf(15);     
        }
        else if((a.equals("PATNY")&&b.equals("TRIMULGHERRY"))||(b.equals("PATNY")&&a.equals("TRIMULGHERRY"))){
            estfare=String.valueOf(60);
            estdis=String.valueOf(5);
            esttime=String.valueOf(15);     
        }
        else if((a.equals("SECUNDERABAD")&&b.equals("PATNY"))||(b.equals("SECUNDERABAD")&&a.equals("PATNY"))){
            estfare=String.valueOf(60);
            estdis=String.valueOf(5);
            esttime=String.valueOf(15);    
        }
        else if((a.equals("TRIMULGHERRY")&&b.equals("ALWAL"))||(b.equals("TRIMULGHERRY")&&a.equals("ALWAL"))){
            estfare=String.valueOf(60);
            estdis=String.valueOf(5);
            esttime=String.valueOf(15);   
        }        
        String[]tmp={estfare,estdis,esttime};
        return tmp;
    }
    
        
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Object i=jComboBox1.getSelectedItem();
        Object k=jComboBox2.getSelectedItem();
        if(i.toString()!=k.toString()){
            String arr[]=givedetail(i.toString(),k.toString());
            jLabel6.setText(arr[0]);
            jLabel9.setText(arr[1]);
            jLabel11.setText(arr[2]);
        }
        else{
            jLabel6.setText("-");
            jLabel11.setText("-");
            jLabel9.setText("-");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        Object i=jComboBox1.getSelectedItem();
        Object k=jComboBox2.getSelectedItem();
        if(i.toString()!=k.toString()){
            String arr[]=givedetail(i.toString(),k.toString());
            jLabel6.setText(arr[0]);
            jLabel9.setText(arr[1]);
            jLabel11.setText(arr[2]);
        }
        else{
            jLabel6.setText("-");
            jLabel11.setText("-");
            jLabel9.setText("-");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        System.out.println(c.ontrip);
        if(c.ontrip.equals("0")){
            Login l=new Login();
            l.z=cnt;
            l.setVisible(true);  
            this.dispose();
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Book b1=new Book(c);
        b1.setVisible(true);
        b1.jLabel7.setText(String.valueOf(c.balance));
        b1.jTextField1.setVisible(false);
        b1.jButton4.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 
        try{
        float amt=Float.parseFloat(jTextField1.getText());

        float tmp=c.addbalance(amt);        
        jLabel7.setText(String.valueOf(tmp));
        jTextField1.setVisible(false);
        jButton4.setVisible(false);
        jButton3.setVisible(true);
        }
        catch(NumberFormatException e){
            jButton4.setVisible(false);
            jButton7.setVisible(true);
        }
        
        
               
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(false);
       
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int ctr=cnt%3;
            if(ctr==0){
                        randomize();
                    }
                  
            float b=c.payamount(x,jLabel6.getText());
            jLabel7.setText(String.valueOf(b));
            jButton6.setVisible(true);
            jButton5.setVisible(false);
            jLabel19.setVisible(true);
            jPanel2.setVisible(false);
            
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Book.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Book.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setVisible(false);
        jLabel9.setVisible(false);
        jLabel8.setVisible(false);
        jLabel11.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Book b2=new Book(c);
        b2.cnt=cnt;
        b2.setVisible(true);
        b2.jLabel7.setText(String.valueOf(c.balance));
        b2.jTextField1.setVisible(false);
        b2.jButton4.setVisible(false);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setVisible(false);
        jButton4.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Book().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollBar jScrollBar1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
